import daisyui from "daisyui";

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        offWhite: "#F1EFEC",
        beige: "#D4C9BE",
        hoverBeige: "rgba(212, 201, 190, 0.3)",
        darkBlue: "#123458",
        nearBlack: "#030303",
        lightGray: "#E5E5E5",
        successGreen: "#4CAF50",
        errorRed: "#F44336",
        fiery: {
          primary: "#E63946",
          secondary: "#F9C74F",
          accent: "#073B4C",
          background: "#F8F9FA",
        },
        dark: {
          primary: "#6C63FF",
          secondary: "#2A2A2A",
          accent: "#00F5D4",
          background: "#121212",
        },
        nature: {
          primary: "#2A9D8F",
          secondary: "#E9C46A",
          accent: "#264653",
          background: "#F7F7F2",
        },
      },
    },
  },
  safelist: [
    // Gradient colors
    "from-beige",
    "to-offWhite",
    "from-fiery-secondary",
    "to-fiery-background",
    "from-dark-secondary",
    "to-dark-background",
    "from-nature-secondary",
    "to-nature-background",

    // Background colors
    "bg-darkBlue",
    "bg-beige",
    "bg-nearBlack",
    "bg-offWhite",
    "bg-successGreen",
    "bg-errorRed",
    "bg-fiery-primary",
    "bg-fiery-secondary",
    "bg-fiery-accent",
    "bg-fiery-background",
    "bg-dark-primary",
    "bg-dark-secondary",
    "bg-dark-accent",
    "bg-dark-background",
    "bg-nature-primary",
    "bg-nature-secondary",
    "bg-nature-accent",
    "bg-nature-background",

    // Hover background colors
    "hover:bg-darkBlue",
    "hover:bg-beige",
    "hover:bg-nearBlack",
    "hover:bg-offWhite",
    "hover:bg-successGreen",
    "hover:bg-errorRed",
    "hover:bg-fiery-primary",
    "hover:bg-fiery-secondary",
    "hover:bg-fiery-accent",
    "hover:bg-fiery-background",
    "hover:bg-dark-primary",
    "hover:bg-dark-secondary",
    "hover:bg-dark-accent",
    "hover:bg-dark-background",
    "hover:bg-nature-primary",
    "hover:bg-nature-secondary",
    "hover:bg-nature-accent",
    "hover:bg-nature-background",

    // Text colors
    "text-darkBlue",
    "text-beige",
    "text-nearBlack",
    "text-offWhite",
    "text-successGreen",
    "text-errorRed",
    "text-fiery-primary",
    "text-fiery-secondary",
    "text-fiery-accent",
    "text-fiery-background",
    "text-dark-primary",
    "text-dark-secondary",
    "text-dark-accent",
    "text-dark-background",
    "text-nature-primary",
    "text-nature-secondary",
    "text-nature-accent",
    "text-nature-background",

    // Hover text colors
    "hover:text-darkBlue",
    "hover:text-beige",
    "hover:text-nearBlack",
    "hover:text-offWhite",
    "hover:text-successGreen",
    "hover:text-errorRed",
    "hover:text-fiery-primary",
    "hover:text-fiery-secondary",
    "hover:text-fiery-accent",
    "hover:text-fiery-background",
    "hover:text-dark-primary",
    "hover:text-dark-secondary",
    "hover:text-dark-accent",
    "hover:text-dark-background",
    "hover:text-nature-primary",
    "hover:text-nature-secondary",
    "hover:text-nature-accent",
    "hover:text-nature-background",
  ],
  plugins: [daisyui],
};
