# Generated by Django 5.2.1 on 2025-05-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0003_genmembershiptype_genshift_secaccess_genperson_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acctraffic',
            name='member',
        ),
        migrations.RemoveField(
            model_name='acctraffic',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='acctraffic',
            name='user',
        ),
        migrations.RemoveField(
            model_name='gensportsanse',
            name='coach_member',
        ),
        migrations.RemoveField(
            model_name='gensportsanse',
            name='membership_type',
        ),
        migrations.RemoveField(
            model_name='gensportsanse',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='gensportsanse',
            name='user',
        ),
        migrations.DeleteModel(
            name='SecAccess',
        ),
        migrations.AlterField(
            model_name='genmember',
            name='has_finger',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='ACCTraffic',
        ),
        migrations.DeleteModel(
            name='GenSportSanse',
        ),
    ]
