# Generated by Django 5.2.1 on 2025-05-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0005_genpersonrole_alter_genmember_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genperson',
            name='birth_date',
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name='genperson',
            name='creation_datetime',
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name='genperson',
            name='ins_end_date',
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name='genperson',
            name='ins_start_date',
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name='genperson',
            name='modification_datetime',
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
    ]
