# Generated by Django 5.2.1 on 2025-05-10 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0006_alter_genperson_birth_date_and_more'),
    ]

    operations = [
    ]
