# Generated by Django 5.2.1 on 2025-05-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0007_auto_20250510_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secuser',
            name='creation_datetime',
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
    ]
