# Generated by Django 5.2.1 on 2025-05-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0008_alter_secuser_creation_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genperson',
            name='has_insurance',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
