# Generated by Django 5.2.1 on 2025-05-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0010_alter_genmember_membership_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genmember',
            name='is_family',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
