# Generated by Django 5.2.1 on 2025-05-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0011_alter_genmember_is_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genmember',
            name='has_finger',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
