# Generated by Django 5.2.1 on 2025-05-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0012_alter_genmember_has_finger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genmember',
            name='member_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genperson',
            name='person_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genpersonrole',
            name='role_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genshift',
            name='shift_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='secuser',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
