# Generated by Django 5.2.1 on 2025-05-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0013_alter_genmember_member_id_alter_genperson_person_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genmember',
            old_name='role_id',
            new_name='role',
        ),
        migrations.RemoveField(
            model_name='genmember',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='genmembershiptype',
            name='membership_type_id',
        ),
        migrations.RemoveField(
            model_name='genperson',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='genpersonrole',
            name='role_id',
        ),
        migrations.RemoveField(
            model_name='genshift',
            name='shift_id',
        ),
        migrations.RemoveField(
            model_name='secuser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='genmember',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='genmembershiptype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='genperson',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='genpersonrole',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='genshift',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='secuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
