# Generated by Django 5.2.1 on 2025-06-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0014_rename_role_id_genmember_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genmember',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genmembershiptype',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genperson',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genpersonrole',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genshift',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='secuser',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
