# Generated by Django 5.2.1 on 2025-06-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0015_alter_genmember_id_alter_genmembershiptype_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genperson',
            name='creation_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='secuser',
            name='creation_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
