# Generated by Django 5.2.1 on 2025-06-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0016_alter_genperson_creation_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genperson',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='secuser',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
