# Generated by Django 5.2.1 on 2025-05-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_vip', models.BooleanField(default=False)),
                ('is_open', models.BooleanField(default=False)),
                ('log', models.JSONField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
